server:
  port: 8888

spring:
  application:
    name: blod
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1449813945
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 20MB
      # 单个文件上传的最大值
      max-file-size: 2MB

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper文件的位置
  mapper-locations: classpath:mappers/*.xml
  # 设置实体类的别名
  # type-aliases-package: com.jxyyxy.blog.entity
  global-config:
    db-config:
      table-prefix: ms_
